// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application";

import SidebarController from "../../components/sidebar/component_controller";

application.register("sidebar", SidebarController);
