version: "3.6"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: dev2021pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  dbadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: default@dieterlunn.ca
      PGADMIN_DEFAULT_PASSWORD: dev2021pass
    ports:
      - 5080:80

  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379

volumes:
  db_data:
